'use strict';
const pad=n=>String(n).padStart(2,'0');
const relationshipStart=new Date(2023,10,16,0,0,0), reunion=new Date(2026,10,19,0,0,0), distanceStart=new Date(2026,8,19,0,0,0);
function calendarDiff(from,to){if(to<from)return{years:0,months:0,days:0,hours:0,minutes:0,seconds:0};let years=to.getFullYear()-from.getFullYear();let anchor=new Date(from);anchor.setFullYear(anchor.getFullYear()+years);if(anchor>to){years--;anchor=new Date(from);anchor.setFullYear(anchor.getFullYear()+years)}let months=0;while(months<11){let n=new Date(anchor);n.setMonth(n.getMonth()+1);if(n>to)break;anchor=n;months++}let ms=to-anchor;const days=Math.floor(ms/86400000);ms-=days*86400000;const hours=Math.floor(ms/3600000);ms-=hours*3600000;const minutes=Math.floor(ms/60000);ms-=minutes*60000;return{years,months,days,hours,minutes,seconds:Math.floor(ms/1000)}}
function updateTimers(){const now=new Date(),d=calendarDiff(relationshipStart,now);tYears.textContent=d.years;tMonths.textContent=d.months;tDays.textContent=d.days;tHours.textContent=pad(d.hours);tMinutes.textContent=pad(d.minutes);tSeconds.textContent=pad(d.seconds);let ms=Math.max(0,reunion-now);cDays.textContent=Math.floor(ms/86400000);ms%=86400000;cHours.textContent=pad(Math.floor(ms/3600000));ms%=3600000;cMinutes.textContent=pad(Math.floor(ms/60000));ms%=60000;cSeconds.textContent=pad(Math.floor(ms/1000))}updateTimers();setInterval(updateTimers,1000);

const memories=[
['assets/moments/product-1.jpg','You. Always.','With you, every ordinary day feels special.'],['assets/moments/product-2.jpg','My safe place.','I still choose you in every version of every day.'],['assets/moments/product-3.jpg','Us, everywhere.','Some memories are places my heart quietly lives in.'],['assets/moments/product-4.jpg','Just us.','Your smile has a way of making the whole day softer.'],['assets/moments/product-5.jpg','My favourite view.','Home has never been a place. It has always felt like you.'],['assets/moments/product-6.jpg','Little moments.','The smallest days with you became my favourite memories.'],['assets/moments/product-7.jpg','Side by side.','Wherever life takes us, I hope we keep finding each other.'],['assets/moments/product-8.jpg','A day to keep.','I love the life hidden inside our ordinary photographs.'],['assets/moments/product-9.png','A page I keep.','We are made of tiny memories that somehow became everything.'],['assets/moments/product-10.png','Still my favourite.','If I had to begin again, I would still look for you.']];
let page=0,busy=false;const book=document.getElementById('book3d'),leftStatic=document.getElementById('leftStatic'),rightStatic=document.getElementById('rightStatic'),curlLayer=document.getElementById('curlLayer'),pageNumber=document.getElementById('pageNumber');
function photoHTML(m){return `<div class="page-inner photo-page"><div class="photo-mat"><img src="${m[0]}" alt="Sriram and Vasanthi memory"></div><p class="photo-note">${m[1]}</p></div>`}
function quoteHTML(m){return `<div class="page-inner quote-page"><div class="quote-copy">${m[2]}</div><div class="quote-ornament">♡</div><div class="sprig-doodle"></div></div>`}
function renderBook(){leftStatic.innerHTML=photoHTML(memories[page]);rightStatic.innerHTML=quoteHTML(memories[page]);pageNumber.textContent=pad(page+1)}renderBook();
function buildNestedCurl(dir,current,next){const leaf=document.createElement('div');leaf.className='curl '+(dir>0?'next':'prev');const shadow=document.createElement('div');shadow.className='leaf-shadow '+(dir>0?'next':'prev');curlLayer.appendChild(shadow);curlLayer.appendChild(leaf);const N=15;let parent=leaf;const strips=[];for(let i=0;i<N;i++){const s=document.createElement('div');s.className='strip';const front=document.createElement('div');front.className='curl-face front';const back=document.createElement('div');back.className='curl-face back';const frontContent=document.createElement('div');frontContent.className='curl-page-clone';frontContent.innerHTML=dir>0?quoteHTML(current):photoHTML(current);const backContent=document.createElement('div');backContent.className='curl-page-clone';backContent.innerHTML=dir>0?photoHTML(next):quoteHTML(next);front.appendChild(frontContent);back.appendChild(backContent);const sh1=document.createElement('div');sh1.className='shade';front.appendChild(sh1);const sh2=document.createElement('div');sh2.className='shade';back.appendChild(sh2);s.append(front,back);parent.appendChild(s);strips.push({s,frontContent,backContent});parent=s}return{leaf,shadow,strips,N}}
function sizeCurl(obj,dir){const rect=(dir>0?rightStatic:leftStatic).getBoundingClientRect(),w=rect.width,h=rect.height,sw=w/obj.N;obj.leaf.style.width=w+'px';obj.strips.forEach((o,i)=>{o.s.style.width=(sw+1)+'px';o.frontContent.style.width=w+'px';o.frontContent.style.height=h+'px';o.backContent.style.width=w+'px';o.backContent.style.height=h+'px';const x=dir>0?-i*sw:-(w-(i+1)*sw);o.frontContent.style.transform=`translateX(${x}px)`;o.backContent.style.transform=`translateX(${x}px)`})}
function ease(t){return t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2}
function turn(dir){if(busy)return;busy=true;const nextIndex=(page+dir+memories.length)%memories.length,current=memories[page],next=memories[nextIndex];if(dir>0)rightStatic.innerHTML=quoteHTML(next);else leftStatic.innerHTML=photoHTML(next);const obj=buildNestedCurl(dir,current,next);sizeCurl(obj,dir);let start=null,duration=1250;function frame(ts){if(!start)start=ts;let raw=Math.min(1,(ts-start)/duration),p=ease(raw),curve=Math.sin(Math.PI*p);obj.leaf.style.transform=`rotateY(${dir>0?-180*p:180*p}deg)`;const bend=curve*3.6;obj.strips.forEach((o,i)=>{if(i>0)o.s.style.transform=`rotateY(${dir>0?-bend:bend}deg)`;const darkness=Math.min(.34,curve*(.08+i/obj.N*.22));o.s.style.setProperty('--shade-a',darkness.toFixed(3));o.s.style.setProperty('--shade-b',(curve*.05).toFixed(3))});obj.shadow.style.opacity=String(curve*.72);obj.shadow.style.transform=`scaleX(${.45+.55*curve})`;if(raw<1)requestAnimationFrame(frame);else{page=nextIndex;renderBook();curlLayer.innerHTML='';busy=false}}requestAnimationFrame(frame)}
prevPage.addEventListener('click',()=>turn(-1));nextPage.addEventListener('click',()=>turn(1));let sx=0;book.addEventListener('touchstart',e=>sx=e.touches[0].clientX,{passive:true});book.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>42)turn(dx<0?1:-1)},{passive:true});addEventListener('resize',()=>{if(busy){curlLayer.innerHTML='';busy=false;renderBook()}});

const monthsEl=document.getElementById('calendarMonths');function buildMonth(year,month){const wrap=document.createElement('section');wrap.className='month-sheet';wrap.dataset.month=month;const title=document.createElement('h3');title.textContent=new Date(year,month,1).toLocaleString('en',{month:'long',year:'numeric'});wrap.appendChild(title);const w=document.createElement('div');w.className='weekdays';['S','M','T','W','T','F','S'].forEach(v=>{const s=document.createElement('span');s.textContent=v;w.appendChild(s)});wrap.appendChild(w);const d=document.createElement('div');d.className='days';for(let i=0;i<new Date(year,month,1).getDay();i++){const x=document.createElement('span');x.className='day empty';d.appendChild(x)}const total=new Date(year,month+1,0).getDate(),today=new Date();today.setHours(0,0,0,0);for(let n=1;n<=total;n++){const date=new Date(year,month,n),x=document.createElement('span');x.className='day';x.textContent=n;if(date<today)x.classList.add('passed');if(date>=distanceStart&&date<=reunion)x.classList.add('long-distance');if(month===10&&n===16)x.classList.add('anniversary');if(month===10&&n===19)x.classList.add('reunion');d.appendChild(x)}wrap.appendChild(d);const legend=document.createElement('div');legend.className='month-legend';legend.innerHTML='<span><i class="passed-dot"></i> Day passed</span><span><i class="distance-dot"></i> Long distance</span><span><i class="anniversary-dot">❀</i> Our anniversary</span><span><i class="reunion-dot">♥</i> Reunion day</span>';wrap.appendChild(legend);return wrap}[8,9,10].forEach(m=>monthsEl.appendChild(buildMonth(2026,m)));

const scenes=[...document.querySelectorAll('.scene')];let raf=0;function updateSceneMotion(){raf=0;const vh=innerHeight;scenes.forEach(s=>{const r=s.getBoundingClientRect(),delta=(r.top+r.height/2-vh/2)/vh;s.dataset.motion=Math.abs(delta)<.32?'active':delta<0?'before':'after'})}addEventListener('scroll',()=>{if(!raf)raf=requestAnimationFrame(updateSceneMotion)},{passive:true});updateSceneMotion();
if(window.THREE){const canvas=document.getElementById('three-canvas'),renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);const sc=new THREE.Scene(),cam=new THREE.PerspectiveCamera(46,innerWidth/innerHeight,.1,100);cam.position.z=8;const group=new THREE.Group();sc.add(group);for(let i=0;i<25;i++){const mat=new THREE.MeshBasicMaterial({color:0xd08b87,transparent:true,opacity:.12,side:THREE.DoubleSide}),g=new THREE.CircleGeometry(.018+Math.random()*.04,8),p=new THREE.Mesh(g,mat);p.position.set((Math.random()-.5)*12,(Math.random()-.5)*16,-2-Math.random()*8);group.add(p)}let mx=0,my=0;addEventListener('pointermove',e=>{mx=(e.clientX/innerWidth-.5)*2;my=(e.clientY/innerHeight-.5)*2},{passive:true});function animate(){cam.position.x+=(mx*.22-cam.position.x)*.03;cam.rotation.x+=(-my*.008-cam.rotation.x)*.03;group.rotation.y+=.0008;group.children.forEach((p,i)=>{p.position.y-=.0008*(i%4+1);if(p.position.y<-9)p.position.y=9});renderer.render(sc,cam);requestAnimationFrame(animate)}animate();addEventListener('resize',()=>{cam.aspect=innerWidth/innerHeight;cam.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)})}
