'use strict';
const pad=n=>String(n).padStart(2,'0');
const relationshipStart=new Date(2023,10,16,0,0,0); // 16 Nov 2023 local
const reunion=new Date(2026,10,19,0,0,0);
const distanceStart=new Date(2026,8,19,0,0,0);
function calendarDiff(from,to){
  if(to<from)return {years:0,months:0,days:0,hours:0,minutes:0,seconds:0};
  let years=to.getFullYear()-from.getFullYear(); let anchor=new Date(from); anchor.setFullYear(anchor.getFullYear()+years); if(anchor>to){years--;anchor=new Date(from);anchor.setFullYear(anchor.getFullYear()+years)}
  let months=0; while(months<11){let n=new Date(anchor);n.setMonth(n.getMonth()+1);if(n>to)break;anchor=n;months++}
  let ms=to-anchor; const days=Math.floor(ms/86400000);ms-=days*86400000;const hours=Math.floor(ms/3600000);ms-=hours*3600000;const minutes=Math.floor(ms/60000);ms-=minutes*60000;const seconds=Math.floor(ms/1000);
  return {years,months,days,hours,minutes,seconds};
}
function updateTimers(){const now=new Date(),d=calendarDiff(relationshipStart,now);tYears.textContent=d.years;tMonths.textContent=d.months;tDays.textContent=d.days;tHours.textContent=pad(d.hours);tMinutes.textContent=pad(d.minutes);tSeconds.textContent=pad(d.seconds);let ms=Math.max(0,reunion-now);cDays.textContent=Math.floor(ms/86400000);ms%=86400000;cHours.textContent=pad(Math.floor(ms/3600000));ms%=3600000;cMinutes.textContent=pad(Math.floor(ms/60000));ms%=60000;cSeconds.textContent=pad(Math.floor(ms/1000))}updateTimers();setInterval(updateTimers,1000);
const memories=[
['assets/moments/product-1.jpg','You. Always.','With you, every ordinary day feels special.'],
['assets/moments/product-2.jpg','My safe place.','I still choose you in every version of every day.'],
['assets/moments/product-3.jpg','Us, everywhere.','Some memories are places my heart quietly lives in.'],
['assets/moments/product-4.jpg','Just us.','Your smile has a way of making the whole day softer.'],
['assets/moments/product-5.jpg','My favourite view.','Home has never been a place. It has always felt like you.'],
['assets/moments/product-6.jpg','Little moments.','The smallest days with you became my favourite memories.'],
['assets/moments/product-7.jpg','Side by side.','Wherever life takes us, I hope we keep finding each other.'],
['assets/moments/product-8.jpg','A day to keep.','I love the life hidden inside our ordinary photographs.'],
['assets/moments/product-9.png','A page I keep.','We are made of tiny memories that somehow became everything.'],
['assets/moments/product-10.png','Still my favourite.','If I had to begin again, I would still look for you.']
];
let page=0,busy=false;const photo=document.getElementById('memoryPhoto'),quote=document.getElementById('memoryQuote'),note=document.getElementById('photoNote'),pageNumber=document.getElementById('pageNumber'),book=document.getElementById('book');
function makeTurnSheet(dir,nextIndex){const current=memories[page],next=memories[nextIndex];const sheet=document.createElement('div');sheet.className=`turn-sheet ${dir>0?'next':'prev'} active`;if(dir>0){sheet.innerHTML=`<div class="turn-face front"><div class="turn-quote">${current[2]}</div></div><div class="turn-face back"><div class="turn-photo"><img src="${next[0]}" alt=""><em>${next[1]}</em></div></div>`}else{sheet.innerHTML=`<div class="turn-face front"><div class="turn-photo"><img src="${current[0]}" alt=""><em>${current[1]}</em></div></div><div class="turn-face back"><div class="turn-quote">${next[2]}</div></div>`}return sheet}
function setPage(target,dir){if(busy)return;busy=true;const next=(target+memories.length)%memories.length;const sheet=makeTurnSheet(dir,next);book.appendChild(sheet);requestAnimationFrame(()=>requestAnimationFrame(()=>sheet.classList.add(dir>0?'flip-next':'flip-prev')));setTimeout(()=>{page=next;const m=memories[page];photo.src=m[0];note.textContent=m[1];quote.textContent=m[2];pageNumber.textContent=pad(page+1)},540);setTimeout(()=>{sheet.remove();busy=false},1080)}
prevPage.onclick=()=>setPage(page-1,-1);nextPage.onclick=()=>setPage(page+1,1);let sx=0;book.addEventListener('touchstart',e=>sx=e.touches[0].clientX,{passive:true});book.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>45)setPage(page+(dx<0?1:-1),dx<0?1:-1)},{passive:true});
// Calendar
const monthsEl=document.getElementById('calendarMonths');function buildMonth(year,month){const wrap=document.createElement('div');wrap.className='month';const title=document.createElement('h3');title.textContent=new Date(year,month,1).toLocaleString('en',{month:'long',year:'numeric'});wrap.appendChild(title);const w=document.createElement('div');w.className='weekdays';'SMTWTFS'.split('').forEach(x=>{const s=document.createElement('span');s.textContent=x;w.appendChild(s)});wrap.appendChild(w);const d=document.createElement('div');d.className='days';for(let i=0;i<new Date(year,month,1).getDay();i++){const x=document.createElement('span');x.className='day empty';d.appendChild(x)}const total=new Date(year,month+1,0).getDate(),today=new Date();today.setHours(0,0,0,0);for(let n=1;n<=total;n++){const date=new Date(year,month,n),x=document.createElement('span');x.className='day';x.textContent=n;if(date<today)x.classList.add('passed');if(date>=distanceStart&&date<=reunion)x.classList.add('long-distance');if(month===10&&n===16){x.classList.add('anniversary');x.title='Our anniversary ♡'}if(month===10&&n===19){x.classList.add('reunion');x.title='Together again ♡'}d.appendChild(x)}wrap.appendChild(d);return wrap}[8,9,10].forEach(m=>monthsEl.appendChild(buildMonth(2026,m)));
// Full-page snap like reference: one wheel gesture = one scene, no loose half-scenes.
const scenes=[...document.querySelectorAll('.scene')];let currentScene=0,scrollLock=false;function nearestScene(){let best=0,dist=Infinity;scenes.forEach((s,i)=>{const v=Math.abs(s.getBoundingClientRect().top);if(v<dist){dist=v;best=i}});return best}function gotoScene(i){i=Math.max(0,Math.min(scenes.length-1,i));if(i===currentScene&&Math.abs(scenes[i].getBoundingClientRect().top)<3)return;currentScene=i;scrollLock=true;scenes[i].scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>scrollLock=false,850)}
addEventListener('wheel',e=>{if(Math.abs(e.deltaY)<18||scrollLock)return;e.preventDefault();currentScene=nearestScene();gotoScene(currentScene+(e.deltaY>0?1:-1))},{passive:false});addEventListener('keydown',e=>{if(['ArrowDown','PageDown',' '].includes(e.key)){e.preventDefault();gotoScene(nearestScene()+1)}if(['ArrowUp','PageUp'].includes(e.key)){e.preventDefault();gotoScene(nearestScene()-1)}if(e.key==='Home'){e.preventDefault();gotoScene(0)}if(e.key==='End'){e.preventDefault();gotoScene(scenes.length-1)}});
let motionRAF=0;function updateSceneMotion(){motionRAF=0;const vh=innerHeight;scenes.forEach(s=>{const r=s.getBoundingClientRect(),center=r.top+r.height/2,delta=(center-vh/2)/vh;let state='far';if(Math.abs(delta)<.28)state='active';else if(delta<0&&delta>-1.2)state='before';else if(delta>0&&delta<1.2)state='after';s.dataset.motion=state});currentScene=nearestScene()}addEventListener('scroll',()=>{if(!motionRAF)motionRAF=requestAnimationFrame(updateSceneMotion)},{passive:true});updateSceneMotion();
// Three.js atmospheric depth synced to section position
if(window.THREE){const canvas=document.getElementById('three-canvas'),renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);const scene3=new THREE.Scene(),camera=new THREE.PerspectiveCamera(46,innerWidth/innerHeight,.1,100);camera.position.set(0,0,8);const group=new THREE.Group();scene3.add(group);const mat=new THREE.MeshBasicMaterial({color:0xd08b87,transparent:true,opacity:.18,side:THREE.DoubleSide});for(let i=0;i<28;i++){const g=new THREE.CircleGeometry(.018+Math.random()*.045,9);const p=new THREE.Mesh(g,mat.clone());p.position.set((Math.random()-.5)*12,(Math.random()-.5)*18,-2-Math.random()*8);p.rotation.z=Math.random()*Math.PI;group.add(p)}let mx=0,my=0,targetY=0,targetZ=8;addEventListener('pointermove',e=>{mx=(e.clientX/innerWidth-.5)*2;my=(e.clientY/innerHeight-.5)*2},{passive:true});function sync3(){const i=nearestScene(),r=scenes[i].getBoundingClientRect(),progress=Math.max(-1,Math.min(1,-r.top/innerHeight));targetY=-i*2.2-progress*1.2;targetZ=8-Math.abs(progress)*.6}addEventListener('scroll',sync3,{passive:true});sync3();const clock=new THREE.Clock();function animate(){const t=clock.getElapsedTime();camera.position.y+=(targetY-camera.position.y)*.045;camera.position.z+=(targetZ-camera.position.z)*.045;camera.position.x+=(mx*.28-camera.position.x)*.03;camera.rotation.x+=(-my*.009-camera.rotation.x)*.03;group.rotation.y=t*.008;group.children.forEach((p,i)=>{p.rotation.z+=.001*(i%3+1);p.position.y-=.001*(i%4+1);if(p.position.y<-12)p.position.y=12});renderer.render(scene3,camera);requestAnimationFrame(animate)}animate();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)})}
